/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { OGUOGU } from "./OGUOGU";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { OGUOGU__factory } from "./factories/OGUOGU__factory";
