version: '3.8'

services:
  db:
    image: postgres
    container_name: oguogu-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}      
    volumes:
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  anvil:
    image: craftsangjae/anvil:latest
    container_name: oguogu-anvil
    ports:
      - 8545:8545

  minio:
    image: minio/minio:latest
    container_name: oguogu-minio
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - 9000:9000
      - 9001:9001

