---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBqb/L/AR/d04+gx1O+cG2xxHbjgKRMSkmojK8FzLDn/xGNaWihFRB5mnum1X+tvX5Ykc3tHpbkogc1ztIHDlkcwec5G6ucXcTsJCbu3eTYdkpsvW6c0jHrKtzjExkY5dnEnANlQ+GgEbHm92Qq63+TjMWeaLpWg4Kp1EWZvSSbwhv8zmFpqH49Z2aTUloAAY9I0D5VQX4659wHvXdmud/hCdIry3rmAJAkQ6XNDta6MGHiJkLAEs4Y2ZZNcewPaFHz8sS3KJ8eqJPgyrLYtF1Ht0EAZoGDrijVwjtqGXUIwXuOEhejt9PHpmLT013BWnpAqUYA7xSYAw/VyAs6xXhRSNDNzQgVPh4Iq6UbgvMfAQskdqklFLnPaVrIxmPt+iSTMyCwdMexPgPkXOlnGBdrjZiSh3dP+vpLcHe29I+hbgmkeCql8WMvlmwYCn3d7jDbiVT1rhoqRnTm8dGRP7PYP8NPBu3vx2xniAMZi1NPlLTdyNfA77WX1dsSuHTylXS0Tr7yGtZTGtWhQMIr4C6hVp3c3px2GL91U2/3dp1bOavnnc5OQruLRhzn8L9W8hRAGVdGduFiMtbn8x53dGFPR9DzlkXGZ+hi5HuRp3COIzyfRAheJ1v4RzZg+NKKFfxnn5AsCS2OXTrbNdLd7FhofXSouNeytVE9JBFUrVNpa0618K4gwgS2+gOKuEbxaLQ1q39ODDHvnQ096jvo9D8aTcFPcZKCCSFWHF61SuTICQ+vuFzxaatp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
