apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: common
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console 
  selector:
    app: minio    

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingress
  namespace: common
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`storage.crafthomelab.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: minio-service
          port: 9000
    - match: Host(`minio-console.crafthomelab.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: minio-service
          port: 9001          
  tls:
    secretName: storage-cert-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storage-cert
  namespace: common
spec:
  commonName: storage.crafthomelab.com
  dnsNames:
    - storage.crafthomelab.com
    - minio-console.crafthomelab.com
  secretName: storage-cert-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: common
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - --console-address
            - ":9001"
            - /data
          ports:
            - containerPort: 9000
            - containerPort: 9001
          envFrom:
            - secretRef:
                name: minio-secret
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
