---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-secret
  namespace: common
spec:
  encryptedData:
    config.yml: AgBTJcM/SHS6lnaoerd4qdCqIyeqWfZyC/S2dnG9beInEl2Nhn5LhoR0Whq9mqA/qTcA6MZdAcF17yGXt2IjDZNrE5oaLi8ads0+M7sttthAg27aBpWN9gwxnHeB5OOwz9n6O7qk/i81FpPFf8dSp7gLURV5X1UsYMTw1HzKibYrE3LkHIWrmX0mXpoLeYjdVs42a26mAAV4lx6uK0kieJ48LqfABM0jIlqC/oK20nqpuwd85PRgtVDVHGFnAry/ffl9OpvLrGE4wjA8MWvgEF2HkQtydcM/ZwC6IoONk0s24mBvKu4y3ldOz+jd6Q2DmNN1c+8kCXYsgsI9xe5yW3Mrl8Sdv/M5JInRWD6x17yotT9Rpsx3XSecFRlDXFpgtlvrk+uW54vaimryw48I8ThmZm0DOFAsfe270TCM/FcRj8PTnd4SrXxxrM2LypDbPe+aMVM47iM/WRa3qAb9OGDSHhYwExbnOqO0I7deMyL/eRsTwBntfdK3U+krkJUnC+TgOrJcbGI1fxuff+yKsHtU15wD4rIPYz8DywFuv7heudWFp1bvcBNSLry7Njrv/J2I0YmzGzC4zsvseUdQ4YAxBq/h3L95EP7hvREZNcCwPV0esOgaD9tmkdonfprI9NoGjiAxF1fDuh2JlVUncfe8+8ARmhR04l5Ta/bmSnOt41LBMStNR2IqE+uNaASiLkPcI1yLWTG6iaDQ8CPrushW3RQtk0yTs7cW4m9SLMsJ56Jng7Bi9J4osTC/8iIAg5Rn0spJ6UzBMFTbPa0bYo/vvApr3EM/Vndh/pdoooqFKTd0um8qanVrg6Jvs0MWNgllJ6GzNKR3m8267ixcB4FUiZavs7Iar+mj/0fisSLnF2MzrWWb/Xs5toTtJpBteNmo+U+U3WuM2aMbjgWGU/5fMR+jtezfQXYzpUN/hvdGRiQGCRuqb9X6LjKlKCq3C0QiZlbR3Bx8ZjAw4ECZeCy/+KFYzC1FjwlHi8zg+kJdcWz65s0p7Jgvh+T/H+V++E5KVb5uFCJL3cH9JjFZpMQZPYHBprdGPOyUAHmh4gfCSqkeusfQvkiwL01xUTypZAj1LF4VzlAWqWQk/B8gFP4BLTj1vccGo63AX+GO3jQwcI2Lj5YsuX4G2RXbwTdqbSoY5gQZcJwOQU39T6W6RdsJgQUzeeAMYr2AYyzD6gPQ+S1dZCW5LI+gQ1QbVsLDQJnuz6XPYRUuWsfJc8Bdxso/e3BRdu+u5tKR1shA8hZFw0l4z8+hFDU7JYfqxHQaNiT0ki37lchrpgZpOPNE0xpzrPcS80/Io5UJCY5X3xsRAqjc8wKDydo1e2FOQrgZkSKl/0s3C7bXCDr8qrdaVF2o346gMuNWjxB/kOkk1u+FFUJCr3CU9MKQaEWdNyvv6Ts5iBzsNF5GKh+8744Oir3z0EVTd88mrEMpOIEJ
  template:
    metadata:
      creationTimestamp: null
      name: registry-secret
      namespace: common
    type: Opaque
